# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 40089838-70DB-4EC9-8865-509BECBB8C53;mulle-storage;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import;
# Disable with : `mulle-sourcetree mark mulle-storage no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-storage no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-storage no-cmake-sdk-<name>`
#
if( NOT MULLE__STORAGE_LIBRARY)
   find_library( MULLE__STORAGE_LIBRARY NAMES
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-storage${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-storage${CMAKE_STATIC_LIBRARY_SUFFIX}
      mulle-storage
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH
   )
   if( NOT MULLE__STORAGE_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
      find_library( MULLE__STORAGE_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-storage${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-storage${CMAKE_STATIC_LIBRARY_SUFFIX}
         mulle-storage
      )
   endif()
   message( STATUS "MULLE__STORAGE_LIBRARY is ${MULLE__STORAGE_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE__STORAGE_LIBRARY)
      #
      # Add MULLE__STORAGE_LIBRARY to DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark mulle-storage no-cmake-add`
      #
      list( APPEND DEPENDENCY_LIBRARIES ${MULLE__STORAGE_LIBRARY})
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark mulle-storage no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE__STORAGE_ROOT "${MULLE__STORAGE_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE__STORAGE_ROOT "${_TMP_MULLE__STORAGE_ROOT}" DIRECTORY)
      #
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark mulle-storage no-cmake-dependency`
      #
      foreach( _TMP_MULLE__STORAGE_NAME "mulle-storage")
         set( _TMP_MULLE__STORAGE_DIR "${_TMP_MULLE__STORAGE_ROOT}/include/${_TMP_MULLE__STORAGE_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE__STORAGE_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__STORAGE_DIR}")
            #
            include( "${_TMP_MULLE__STORAGE_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__STORAGE_DIR}")
            #
            unset( MULLE__STORAGE_DEFINITIONS)
            include( "${_TMP_MULLE__STORAGE_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE__STORAGE_DEFINITIONS})
            break()
         else()
            message( STATUS "${_TMP_MULLE__STORAGE_DIR} not found")
         endif()
      endforeach()
   else()
      # Disable with: `mulle-sourcetree mark mulle-storage no-require-link`
      message( FATAL_ERROR "MULLE__STORAGE_LIBRARY was not found")
   endif()
endif()
