# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Set library preference based on BUILD_SHARED_LIBS
#
if( BUILD_SHARED_LIBS)
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
else()
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
endif()

#
# Generated from sourcetree: 8DB1697D-A19C-40A1-A1A8-8DE1A4444CC2;mulle-rbtree;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import;
# Disable with : `mulle-sourcetree mark mulle-rbtree no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-rbtree no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-rbtree no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "mulle-rbtree")
else()
   if( NOT MULLE__RBTREE_LIBRARY)
      foreach( _TMP_MULLE__RBTREE_LIBRARY_TARGET mulle-rbtree)
         if( TARGET ${_TMP_MULLE__RBTREE_LIBRARY_TARGET})
            set( MULLE__RBTREE_LIBRARY ${_TMP_MULLE__RBTREE_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__RBTREE_LIBRARY)
         find_library( MULLE__RBTREE_LIBRARY NAMES
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-rbtree${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-rbtree${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-rbtree${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-rbtree${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-rbtree
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__RBTREE_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__RBTREE_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-rbtree${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-rbtree${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-rbtree${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-rbtree${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-rbtree
            )
         endif()
      endif()
      message( STATUS "MULLE__RBTREE_LIBRARY is ${MULLE__RBTREE_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__RBTREE_LIBRARY)
         #
         # Add MULLE__RBTREE_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-rbtree no-cmake-add`
         #
         list( APPEND DEPENDENCY_LIBRARIES ${MULLE__RBTREE_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-rbtree no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__RBTREE_ROOT "${MULLE__RBTREE_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__RBTREE_ROOT "${_TMP_MULLE__RBTREE_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-rbtree no-cmake-dependency`
         #
         foreach( _TMP_MULLE__RBTREE_NAME "mulle-rbtree")
            set( _TMP_MULLE__RBTREE_DIR "${_TMP_MULLE__RBTREE_ROOT}/include/${_TMP_MULLE__RBTREE_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__RBTREE_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__RBTREE_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__RBTREE_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__RBTREE_DIR}")
               #
               unset( MULLE__RBTREE_DEFINITIONS)
               unset( MULLE__RBTREE_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__RBTREE_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__RBTREE_DEFINITIONS})
               include( "${_TMP_MULLE__RBTREE_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__RBTREE_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__RBTREE_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-rbtree no-require-link`
         message( SEND_ERROR "MULLE__RBTREE_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-rbtree${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-rbtree${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-rbtree${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-rbtree${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-rbtree")
      endif()
   endif()
endif()


#
# Generated from sourcetree: B5503F2F-7B31-414A-9C02-4951D21E79C6;mulle-fprintf;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import;
# Disable with : `mulle-sourcetree mark mulle-fprintf no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-fprintf no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-fprintf no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "mulle-fprintf")
else()
   if( NOT MULLE__FPRINTF_LIBRARY)
      foreach( _TMP_MULLE__FPRINTF_LIBRARY_TARGET mulle-fprintf)
         if( TARGET ${_TMP_MULLE__FPRINTF_LIBRARY_TARGET})
            set( MULLE__FPRINTF_LIBRARY ${_TMP_MULLE__FPRINTF_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__FPRINTF_LIBRARY)
         find_library( MULLE__FPRINTF_LIBRARY NAMES
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-fprintf${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-fprintf${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-fprintf${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-fprintf${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-fprintf
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__FPRINTF_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__FPRINTF_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-fprintf${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-fprintf${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-fprintf${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-fprintf${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-fprintf
            )
         endif()
      endif()
      message( STATUS "MULLE__FPRINTF_LIBRARY is ${MULLE__FPRINTF_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__FPRINTF_LIBRARY)
         #
         # Add MULLE__FPRINTF_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-fprintf no-cmake-add`
         #
         list( APPEND DEPENDENCY_LIBRARIES ${MULLE__FPRINTF_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-fprintf no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__FPRINTF_ROOT "${MULLE__FPRINTF_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__FPRINTF_ROOT "${_TMP_MULLE__FPRINTF_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-fprintf no-cmake-dependency`
         #
         foreach( _TMP_MULLE__FPRINTF_NAME "mulle-fprintf")
            set( _TMP_MULLE__FPRINTF_DIR "${_TMP_MULLE__FPRINTF_ROOT}/include/${_TMP_MULLE__FPRINTF_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__FPRINTF_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__FPRINTF_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__FPRINTF_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__FPRINTF_DIR}")
               #
               unset( MULLE__FPRINTF_DEFINITIONS)
               unset( MULLE__FPRINTF_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__FPRINTF_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__FPRINTF_DEFINITIONS})
               include( "${_TMP_MULLE__FPRINTF_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__FPRINTF_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__FPRINTF_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-fprintf no-require-link`
         message( SEND_ERROR "MULLE__FPRINTF_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-fprintf${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-fprintf${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-fprintf${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-fprintf${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-fprintf")
      endif()
   endif()
endif()
